name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Daily Scrapy Run"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    # if: ${{ always() }}
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    if: ${{ github.event.workflow_run.conclusion != 'cancelled' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate dynamic dashboard
        run: |
          mkdir -p public
          echo "<html><body><h1>Recent Scraper Runs</h1><table border=1>" > public/index.html
          gh api repos/${{ github.repository }}/actions/workflows/scraper.yaml/runs \
            --jq '.workflow_runs[:10][] | "<tr><td>\(.run_number)</td><td>\(.conclusion)</td><td>\(.updated_at)</td></tr>"' \
            >> public/index.html
          echo "</table></body></html>" >> public/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
